targetNamespace: ''
parameters: {}
packages:
  - name: glitchtip-webhook
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: handler
        runtime: 'nodejs:18'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
